import logging
from typing import Any, Optional

import numpy as np
from sentence_transformers import SentenceTransformer

from .cache import EmbeddingCache

logger = logging.getLogger(__name__)


class Embedding:
    """Embedding generation class with caching support."""

    cache: Optional[EmbeddingCache]

    def __init__(
        self,
        model_name_or_path: str,
        device: str | None = None,
        cache_folder: str | None = None,
        trust_remote_code: bool = False,
        enable_cache: bool = True,
        embedding_cache: str | None = None,
        max_shard_size: int = 10000,
        enable_hash_sharding: bool = True,
    ):
        """Initialize the embedding model.        Args:
        model_name_or_path: Name or path of the SentenceTransformer model
        device: Device to run the model on (e.g., 'cuda', 'cpu')
        cache_folder: Folder to cache model files
        trust_remote_code: Whether to trust remote code
        enable_cache: Whether to enable embedding caching
        embedding_cache: Directory for embedding cache files
        max_shard_size: Maximum number of embeddings per shard file
        enable_hash_sharding: Use hash-based sharding for better distribution
        """
        self.model_name_or_path = model_name_or_path
        self.enable_cache = enable_cache

        logger.info(f"Initializing embedding model: {model_name_or_path}")

        self.model = SentenceTransformer(
            model_name_or_path,
            device=device,
            cache_folder=cache_folder,
            trust_remote_code=trust_remote_code,
        )

        # Initialize cache if enabled
        if self.enable_cache:
            self.cache = EmbeddingCache(cache_dir=embedding_cache)
            logger.info("Embedding cache enabled")
        else:
            self.cache = None
            logger.info("Embedding cache disabled")

        logger.info("Embedding model initialization completed")

    def embed(
        self, texts: list[str], batch_size: int = 32
    ) -> np.ndarray[Any, np.dtype[np.float32]]:
        """Generate embeddings for given texts with caching support.

        Args:
            texts: List of texts to embed
            batch_size: Batch size for processing

        Returns:
            NumPy array of embeddings
        """
        logger.debug(f"Starting embedding generation: {len(texts)} texts")

        # Try to get embeddings from cache first
        if self.enable_cache and self.cache is not None:
            cached_embeddings = self.cache.get_embeddings(
                texts, self.model_name_or_path
            )
            if cached_embeddings is not None:
                logger.info(f"Found cached embeddings for {len(texts)} texts")
                return cached_embeddings

        # Generate embeddings if not in cache
        logger.debug("Computing new embeddings...")
        embeddings = self.model.encode(
            texts,
            convert_to_numpy=True,
            normalize_embeddings=True,
            batch_size=batch_size,
        )

        # Save to cache if enabled
        if self.enable_cache and self.cache is not None:
            self.cache.save_embeddings(texts, self.model_name_or_path, embeddings)
            logger.debug("Embeddings saved to cache")

        logger.debug(f"Embedding generation completed: {embeddings.shape}")
        return embeddings

    def get_dimension(self) -> int:
        """Get the dimension of embeddings generated by this model."""
        dummy_embedding = self.embed(["test"])
        return dummy_embedding.shape[1]
